version: '3.6'

services:
  traefik:
    image: traefik:latest 
    ports:
      - "80:80"     
      - "443:443"     
      - "8080:8080"  
    labels:
      - "traefik.frontend.rule=Host:$MONITOR_DOMAIN"
      - "traefik.port=8080"
    restart: always
    environment:
      - LEXICON_SLEEP_TIME=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme/acme.json:/etc/traefik/acme/acme.json
    container_name: traefik

  mariaDB:
    image: mariadb:latest
    container_name: mariaDB
    restart: always
    volumes:
     - ./database:/var/lib/mysql:rw
    ports:
     - "3306:3306" 
    labels:
     - "traefik.enable=false" 
    environment:
     - MYSQL_ROOT_PASSWORD=$MYSQL_PASS

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    labels:
     - "traefik.frontend.rule=Host:$DB_DOMAIN"
    environment:        
     - PMA_ARBITRARY=1
    depends_on:
     - mariaDB

  wordpress:
    image: wordpress
    container_name: wordpress_1
    restart: always
    depends_on:
      - mariaDB
    environment:
     - WORDPRESS_DB_HOST=$DB_HOST
     - WORDPRESS_DB_NAME=$DB_NAME
     - WORDPRESS_TABLE_PREFIX=$DB_PREFIX
     - WORDPRESS_DB_USER=$DB_USER
     - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html # Full wordpress project
    labels:
      - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN"      
